/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingReviewRouteImport } from './routes/onboarding.review'
import { Route as OnboardingMenuRouteImport } from './routes/onboarding.menu'
import { Route as InvoiceSentRouteImport } from './routes/invoice.sent'
import { Route as InvoiceReviewRouteImport } from './routes/invoice.review'
import { Route as InvoiceProcessingRouteImport } from './routes/invoice.processing'
import { Route as InvoiceNewRouteImport } from './routes/invoice.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingReviewRoute = OnboardingReviewRouteImport.update({
  id: '/onboarding/review',
  path: '/onboarding/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMenuRoute = OnboardingMenuRouteImport.update({
  id: '/onboarding/menu',
  path: '/onboarding/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceSentRoute = InvoiceSentRouteImport.update({
  id: '/invoice/sent',
  path: '/invoice/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceReviewRoute = InvoiceReviewRouteImport.update({
  id: '/invoice/review',
  path: '/invoice/review',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceProcessingRoute = InvoiceProcessingRouteImport.update({
  id: '/invoice/processing',
  path: '/invoice/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceNewRoute = InvoiceNewRouteImport.update({
  id: '/invoice/new',
  path: '/invoice/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invoice/new': typeof InvoiceNewRoute
  '/invoice/processing': typeof InvoiceProcessingRoute
  '/invoice/review': typeof InvoiceReviewRoute
  '/invoice/sent': typeof InvoiceSentRoute
  '/onboarding/menu': typeof OnboardingMenuRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoice/new': typeof InvoiceNewRoute
  '/invoice/processing': typeof InvoiceProcessingRoute
  '/invoice/review': typeof InvoiceReviewRoute
  '/invoice/sent': typeof InvoiceSentRoute
  '/onboarding/menu': typeof OnboardingMenuRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invoice/new': typeof InvoiceNewRoute
  '/invoice/processing': typeof InvoiceProcessingRoute
  '/invoice/review': typeof InvoiceReviewRoute
  '/invoice/sent': typeof InvoiceSentRoute
  '/onboarding/menu': typeof OnboardingMenuRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invoice/new'
    | '/invoice/processing'
    | '/invoice/review'
    | '/invoice/sent'
    | '/onboarding/menu'
    | '/onboarding/review'
    | '/onboarding/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoice/new'
    | '/invoice/processing'
    | '/invoice/review'
    | '/invoice/sent'
    | '/onboarding/menu'
    | '/onboarding/review'
    | '/onboarding/welcome'
  id:
    | '__root__'
    | '/'
    | '/invoice/new'
    | '/invoice/processing'
    | '/invoice/review'
    | '/invoice/sent'
    | '/onboarding/menu'
    | '/onboarding/review'
    | '/onboarding/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvoiceNewRoute: typeof InvoiceNewRoute
  InvoiceProcessingRoute: typeof InvoiceProcessingRoute
  InvoiceReviewRoute: typeof InvoiceReviewRoute
  InvoiceSentRoute: typeof InvoiceSentRoute
  OnboardingMenuRoute: typeof OnboardingMenuRoute
  OnboardingReviewRoute: typeof OnboardingReviewRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/review': {
      id: '/onboarding/review'
      path: '/onboarding/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof OnboardingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/menu': {
      id: '/onboarding/menu'
      path: '/onboarding/menu'
      fullPath: '/onboarding/menu'
      preLoaderRoute: typeof OnboardingMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/sent': {
      id: '/invoice/sent'
      path: '/invoice/sent'
      fullPath: '/invoice/sent'
      preLoaderRoute: typeof InvoiceSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/review': {
      id: '/invoice/review'
      path: '/invoice/review'
      fullPath: '/invoice/review'
      preLoaderRoute: typeof InvoiceReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/processing': {
      id: '/invoice/processing'
      path: '/invoice/processing'
      fullPath: '/invoice/processing'
      preLoaderRoute: typeof InvoiceProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/new': {
      id: '/invoice/new'
      path: '/invoice/new'
      fullPath: '/invoice/new'
      preLoaderRoute: typeof InvoiceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvoiceNewRoute: InvoiceNewRoute,
  InvoiceProcessingRoute: InvoiceProcessingRoute,
  InvoiceReviewRoute: InvoiceReviewRoute,
  InvoiceSentRoute: InvoiceSentRoute,
  OnboardingMenuRoute: OnboardingMenuRoute,
  OnboardingReviewRoute: OnboardingReviewRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
